version: '3'
services:

  db:
    image: mongo:5.0.12
    container_name: db
    ports:
     - "27017:27017"
    restart: always

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    volumes:
     - /auth/node_modules
     - ./auth:/auth
    ports:
     - "8080:8080"
    depends_on:
     - db
    restart: always

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
     - /gateway/node_modules
     - ./gateway:/gateway
    ports:
     - "3000:3000"
    depends_on:
     - auth
    restart: always