version: '3'
services:

  db:
    image: mongo:5.0.12
    container_name: db
    ports:
     - "27017:27017"
    volumes:
      - mongodb:/data/db
    restart: always

  auth:
    build: 
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    volumes:
     - /auth/node_modules
     - ./auth:/auth
    depends_on:
     - db
    restart: always
  
  products:
    build: 
      context: ./products-manager
      dockerfile: Dockerfile
    container_name: products
    volumes:
     - /products/node_modules
     - ./products-manager:/products
    depends_on:
     - db
    restart: always

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    volumes:
     - /gateway/node_modules
     - ./gateway:/gateway
    ports:
     - "3000:3000"
    depends_on:
     - auth
     - products
    restart: always
volumes:
  mongodb: